/* Lift the rules and the content out of the pass-and-play build into a server
   module, so the two never drift apart. Everything view-shaped is left behind.

   Run:  node game/build-engine.js /path/to/buzz.html                        */
"use strict";
const fs = require("fs");
const path = require("path");

/* ---------------------------------------------------------------------------
   This no longer runs, and must not.

   game/engine.js began life here, lifted out of the pass-and-play build. It
   has since grown four game modes, six maps, the wildcard square, the board's
   own balance and a scoring scale — none of which exist in any buzz.html.
   Regenerating produces roughly six hundred lines against the engine's eight
   hundred and takes the rest with it, and play.js stops finding its exports
   the moment it loads.

   The file is kept because it records how the engine was first assembled and
   which parts of the original build were left behind. To change the rules,
   edit game/engine.js.                                                       */
console.error(
  "game/build-engine.js does not run any more.\n" +
  "game/engine.js is written by hand — regenerating would delete the game\n" +
  "modes, the maps, the wildcard square and the board balance. Edit the\n" +
  "engine directly; npm test and npm run playtest are the net.");
process.exit(1);

const src = process.argv[2];
if(!src){ console.error("usage: node game/build-engine.js <buzz.html>"); process.exit(1); }
const html = fs.readFileSync(src, "utf8");
const lines = html.split("\n");

/* Find the sections by their own banner comments rather than by line number,
   so an edit to the game above them cannot silently shift the slice. */
function lineOf(pred, from){
  for(let i = (from || 0); i < lines.length; i++) if(pred(lines[i])) return i;
  throw new Error("marker not found");
}
const startLang   = lineOf(l => l.startsWith("/* ============ language ============"));
const startBoardV = lineOf(l => l.startsWith("function boardSVG("));       // view: stop here
const startState  = lineOf(l => l.startsWith("/* ============ state ============"));
const startRound  = lineOf(l => l.startsWith("/* ============ a round ============"));
const startRender = lineOf(l => l.startsWith("/* ============ render ============"));

const drop = new Set();
[
  l => l.includes("document.documentElement.dir"),
  l => l.includes("document.documentElement.lang"),
  l => l.startsWith("const app = document.getElementById"),
  l => l.startsWith("const LS = "),
  l => l.startsWith("function save()"),
  l => l.startsWith("function load()")
].forEach(pred => {
  for(let i = 0; i < lines.length; i++) if(pred(lines[i])) drop.add(i);
});

function take(a, b){
  const out = [];
  for(let i = a; i < b; i++) if(!drop.has(i)) out.push(lines[i]);
  return out.join("\n");
}

const body = [
  take(startLang, startBoardV),     // language, all content, the board maths
  take(startState, startRender)     // state helpers, the round, the scoring
    .split("\n")
    .filter(l => !l.startsWith("/* ============ render"))
    .join("\n")
].join("\n\n");

/* things the server calls; everything else stays private to the closure */
const EXPORTS = [
  "applyLang","t","freshState","shuffle","esc",
  "playerById","unitById","unitOf","teammate",
  "newRound","scoreRound","elapsedMs","remainMs","pauseClock","resumeClock",
  "dealTopic","wordValue","valueDelta","initials",
  "ROWS","setBoard","boardRows","nodeTypeAt","isCardNode","colColor",
  "startPos","posOf","atFinish","nextFrom","reachable","modOf","nodeXY","key"
];
const CONSTS = ["CHALLENGES","UNIT_COLORS","COLS","TYPE_PATTERN"];

const out = `/* GENERATED by game/build-engine.js — do not edit by hand.
   Source of truth: the pass-and-play build's rules and content.
   Regenerate with:  node game/build-engine.js <buzz.html>                    */
"use strict";

/* One engine per room. Every extracted function closes over this instance's
   own \`S\`, so two rooms can never see each other's state. */
function createEngine(){
${body.split("\n").map(l => l ? "  " + l : "").join("\n")}

  return {
    get S(){ return S; },
    set S(v){ S = v; },
${EXPORTS.map(n => "    " + n + ",").join("\n")}
${CONSTS.map(n => "    get " + n + "(){ return " + n + "; },").join("\n")}
    packs(){ return { W, CARDS, MODS, TOPICS, TIER, CARDKEYS, D }; }
  };
}

module.exports = { createEngine };
`;

const dest = path.join(__dirname, "engine.js");
fs.writeFileSync(dest, out, "utf8");
console.log("wrote " + dest + "  (" + out.split("\n").length + " lines)");
